#!/bin/sh
# check battery status with respect to charging status
state=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep 'state' | awk '{print $2}')
life=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep 'time to empty' | awk '{print "battery life: " $4,$5}')
perc=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep 'percent' | awk '{print $1,$2}')

# check if charging
if [ $state == "charging" ]; then
    echo "I'm charging"
else
    echo $life
fi

# print battery percentage
echo $perc
