#!/bin/sh
# determine line count recursively
# a particular file extension is optional
if [ $2 != "" ]; then
    ext=$2
else
    ext='*'
fi

echo "looking for $ext in $1"

find $1 -name "$ext"| xargs wc -l
