#!/bin/sh
# Use this script to show disk usage in tmux' statusbar.
# root=$(df -h | grep 'root' | awk '{print $4}')
# home=$(df -h | grep 'home' | awk '{print $4}')
#
# printf "%s %s" "$root" "$home"

disk_name='/dev/sda'
total=$(df -h | grep $disk_name | awk '{printf "%s (%s used)", $4, $5}')

printf "%s" "$total"
