#!/bin/sh
# Create a temp file and open it in a text editor. Automatic removal is done
# with `--remove' or `-r'.
printf "Using %s as an editor.\n" "$EDITOR"
tmpfile=$(mktemp -p .)
printf "Created temporary file %s.\n" "$tmpfile"

# open temporary file with selected editor
"$EDITOR" "$tmpfile"

# conditionally remove temporary file
if [ "$1" = '--remove' ] || [ "$1" = '-r' ]; then
    printf "Removing temporary file %s.\n" "$tmpfile"
    rm "$tmpfile"
fi
