.TH MAKE_HEX 1
.SH NAME
make_hex \- print a decimal number in binary, hexadecimal, and octal formats
.SH SYNOPSIS
.B make_hex
\fB\-n\fR \fINUMBER\fR
.SH DESCRIPTION
.B make_hex
lets you view the binary, hexadecimal, and octal representations of a decimal number.
.SH OPTIONS
.TP
.BR \-n\ \fINUMBER\fR
Indicates which number to print in different formats. This option is required.
.SH AUTHOR
Written by Daniel Schuette.
.SH COPYRIGHT
This is free software, \fBmake_hex\fR is licensed under an GPLv3 license and can be used and redistributed under its terms and conditions. Visit <https://github.com/DanielSchuette/bin> for more information.
.SH REPORTING BUGS
Please open an issue at <https://github.com/DanielSchuette/bin>.
