.TH MARIO 1
.SH NAME
mario \- have an ASCII art mario run over your screen
.SH SYNOPSIS
.B mario
[\fB\-f\fR \fIFRAMERATE\fR]
.SH DESCRIPTION
.B mario
lets an ASCII art mario run from left to right.
.SH OPTIONS
.TP
.BR \-f\ \fIFRAMERATE\fR
Sets the framerate of the mario animation. Default is 10 frames per second.
.SH AUTHOR
Written by Daniel Schuette.
.SH COPYRIGHT
This is free software, \fBmario\fR is licensed under an MIT license and can be used and redistributed under its terms and conditions. Visit <https://github.com/DanielSchuette/bin> for more information.
.SH REPORTING BUGS
Please open an issue at <https://github.com/DanielSchuette/bin>.
