.TH MARIO 1
.SH NAME
mario \- have an ASCII art mario run over your screen
.SH SYNOPSIS
.B mario
[\fB\-f\fR \fIFRAMERATE\fR]
.IR file ...
.SH DESCRIPTION
.B mario
lets an ASCII art mario run from left to right.
.SH OPTIONS
.TP
.BR \-f  =\fIFRAMERATE\fR
Sets the framerate of the mario animation.
Default is 10 frames per second.
